blank_issues_enabled: false
contact_links:
  - name: Question or Suggestions
    url: https://growi-slackin.weseek.co.jp/
    about: If you have questions or suggestions, you can join our Slack team and talk about anything, anytime.
